apiVersion: v2
name: mosquitto
description: Eclipse Mosquitto MQTT Broker Helm Chart
type: application
version: 0.1.0
appVersion: "2.0.18"
keywords:
  - mqtt
  - mosquitto
  - messaging
  - iot
home: https://mosquitto.org
sources:
  - https://github.com/eclipse/mosquitto
maintainers:
  - name: Your Name
    email: your-email@example.com 