replicaCount: 1

image:
  repository: eclipse-mosquitto
  tag: "2.0.18"
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  mqtt:
    port: 1883
  mqtts:
    port: 8883
  websockets:
    port: 9001

persistence:
  enabled: true
  storageClass: "longhorn"
  accessMode: ReadWriteOnce
  size: 1Gi
  retain: true

# Authentication configuration
auth:
  enabled: false  # Set to true to enable password authentication
  # When enabled, you'll need to create users manually or use init containers

config:
  mosquitto.conf: |
    # Persistence
    persistence true
    persistence_location /mosquitto/data/
    
    # Logging
    log_dest file /mosquitto/log/mosquitto.log
    log_dest stdout
    log_type error
    log_type warning
    log_type notice
    log_type information
    connection_messages true
    log_timestamp true
    
    # Authentication
    {{- if .Values.auth.enabled }}
    allow_anonymous false
    password_file /mosquitto/config/passwords
    {{- else }}
    allow_anonymous true
    {{- end }}
    
    # Default MQTT port
    listener 1883
    protocol mqtt
    
    # WebSocket support
    listener 9001
    protocol websockets
    
    # MQTT over TLS/SSL (when certificates are available)
    listener 8883
    protocol mqtt
    cafile /etc/ssl/certs/ca-certificates.crt

resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

nodeSelector: {}

tolerations: []

affinity: {}

env:
  TZ: "America/Chicago" 