apiVersion: v1
kind: Service
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.mqtt.port }}
      targetPort: mqtt
      protocol: TCP
      name: mqtt
    - port: {{ .Values.service.mqtts.port }}
      targetPort: mqtts
      protocol: TCP
      name: mqtts
    - port: {{ .Values.service.websockets.port }}
      targetPort: websockets
      protocol: TCP
      name: websockets
  selector:
    {{- include "mosquitto.selectorLabels" . | nindent 4 }} 